[build]
  base = "frontend"
  command = "npm install && npm install -D vite @vitejs/plugin-react typescript && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 