[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "development"
  NODE_VERSION = "18"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 